### ISSUE TITLE
Installation of CRW

### ISSUE THREAD

**Issue by pdaverh** [codeready-toolchain/toolchain-infra#22]
Can we add installation for CRW, in addition to the one we have for Che?

**Comment by alexeykazakov** [comment]
What do you mean by "in addition"?
It wouldn't make much sense to install both CRW and Che, so, I guess you mean something else?

**Comment by pdaverh** [comment]
From the operator's perspective - yes does not make sense to install both Che and CRW. But if we were to apply the YAMLs separately, then it would be good to have the CRW YAMLs in this rep, though the script can be modified to deploy either CRW or Che.

**Comment by alexeykazakov** [comment]
Ah ok. I see what you mean. Just to add the yamls for CRW installation without actually installing it by the script yet.
Makes sense.

**Comment by alexeykazakov** [comment]
See https://github.com/codeready-toolchain/toolchain-infra/pull/23
